### ISSUE TITLE
HTTPS support?

### ISSUE THREAD

**Issue by hnkien** [lpereira/lwan#144] opened 2016-05-17 02:15 UTC
Do you have plan to support HTTPS protocol?
Thank you very much!

**Comment by lpereira** [comment] 2016-05-25 01:09
Thanks for reporting the issue! Yes, HTTPS is planned. Currently, there's no way to have HTTPS in Lwan without a terminator proxy; luckily, it supports the PROXY protocol, so you can use something like Hitch.

This is a duplicate of #12. I'm closing this issue; if you have further comments, please comment in issue #12 instead.

**Closed by lpereira** 2016-05-25 01:09 UTC
