### ISSUE TITLE
Can't make lwan

### ISSUE THREAD

**Issue by alex-bender** [lpereira/lwan#209] opened 2017-10-19 10:57 UTC
System: Debian 8
```
uname -a
Linux bender 4.9.0-0.bpo.2-amd64 #1 SMP Debian 4.9.13-1~bpo8+1 (2017-02-27) x86_64 GNU/Linux
```
```
cmake .. -DCMAKE_BUILD_TYPE=Release
[...]
/usr/bin/ld: /tmp/ccadO1lz.ltrans0.ltrans.o: relocation R_X86_64_PC32 against symbol `coro_swapcontext' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
src/lib/CMakeFiles/lwan-shared.dir/build.make:86: recipe for target 'src/lib/liblwan.so' failed
make[2]: *** [src/lib/liblwan.so] Error 1
CMakeFiles/Makefile2:162: recipe for target 'src/lib/CMakeFiles/lwan-shared.dir/all' failed
make[1]: *** [src/lib/CMakeFiles/lwan-shared.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by lpereira** [comment] 2017-10-21 00:22
That's odd. I'll try to reproduce this tonight on a pristine Debian 8
install and report back.

**Comment by lpereira** [comment] 2017-10-27 04:15
@alex-bender This seems to be fixed now -- tested and reproduced on an up-to-date Debian 8 installation.   Please confirm; feel free to reopen if it's still broken for you.

**Closed** 2017-10-27 04:14 UTC

**Comment by alex-bender** [comment] 2017-10-28 09:50
@lpereira thanks, it works!
