### ISSUE TITLE
http2 and http3 necessary to be a serious server

### ISSUE THREAD

**Issue by hiqsociety** [lpereira/lwan#307] opened 2021-09-07 13:27 UTC
http2 and http3 necessary to be a serious server.

possible to work on this? once finished i can donate a few cups of coffee :)

**Comment by lpereira** [comment] 2021-09-07 16:56
Closing as duplicate of #17.

I'm taking a break from Lwan, so it's unlikely I'll work on this anytime soon.  HTTP/2 requires TLS, which isn't available at the moment, and would require some deep changes that I don't really want to do. If someone really wants this feature, however, I'm open to pull requests, or even working with people that wants to implement this properly.

**Closed by lpereira** 2021-09-07 16:56 UTC
