### ISSUE TITLE
Slow and responds only on every second request

### ISSUE THREAD

**Issue by acrolink** [lpereira/lwan#163] opened 2016-07-22 09:29 UTC
The benchmark results are very slow, slower than the slowest solution I have ever tested using ab/httperf. The remarkable thing can be seen in the web browser, the server responds on every second request. I hit F5 it loads, again F5 doesn't, F5 responds, F5 not ...

I have installed Iwan on OpenSuse 42.1 64bit..

I am sure these is something wrong here, the question what :+1: As I read this server can serve millions of requests per second.

**Comment by lpereira** [comment] 2016-07-22 10:52
That's indeed pretty curious. I'll try to reproduce that with this version of OpenSuse and see if I notice anything out of the ordinary.

**Comment by acrolink** [comment] 2016-07-22 11:23
Thanks @lpereira I will test also using other tools. I built a release version, More info: the no response issue on web browser is observed on Chrome, Postman tool shows no such problem, but still ab took ages to complete 500 requests.

**Comment by lpereira** [comment] 2016-07-23 00:23
I've installed the same version of OpenSUSE on a virtual machine on my laptop and couldn't reproduce what you're seeing.

Opening things on a browser works alright, and using [weighttp with pipelined patches](https://github.com/gstrauss/weighttp/), I can get up to 550000 requests/second. Without pipelining, but with keep-alive connections, I get about 140000 requests/second; it's slower than what I usually get without it running on a VM (which is usually twice that much).

In all cases, all of the million requests went through fine (200 response code).

If I test using ab, I get similar results to weighttp (albeit I can't get good results with concurrency higher than 100). Running `ab -c 100 -n 1000000 -k http://localhost:8080/hello` yields about 130000 requests/second.

For some reason, `ab` doesn't seem to work with Lwan when using non-keepalive connections; using `weighttp` with non-keepalive connections seem to work fine, yielding an alright 20000 requests/second. (Which is usually twice as much when running outside the VM.)

**Comment by lpereira** [comment] 2017-03-24 03:41
Closing as I couldn't reproduce this issue.

**Closed by lpereira** 2017-03-24 03:41 UTC
