### ISSUE TITLE
Websocket support feature

### ISSUE THREAD

**Issue by Globik** [lpereira/lwan#230] opened 2018-05-04 18:42 UTC
It would be nice to have websocket.

**Comment by lpereira** [comment] 2018-05-10 23:54
Closing as duplicate of #17.

**Comment by lpereira** [comment] 2018-09-17 02:10
Reopening this issue: issue #17 has been modified to track only implementation of HTTP/2.  Experimental websockets has been pushed to the `websockets-experimental` branch.

**Comment by alexhultman** [comment] 2018-11-12 15:20
Is lwan_response_websocket_read supposed to work by now?

I can run the websocket sample but when I modify it to wait for data, lwan_response_websocket_read call just eats control flow and disconnects the client.

Something like this:

```
LWAN_HANDLER(ws)
{
    enum lwan_http_status status = lwan_request_websocket_upgrade(request);

    if (status != HTTP_SWITCHING_PROTOCOLS)
        return status;

    while (true) {
        lwan_response_websocket_read(request)
        lwan_response_websocket_write(request);
    }

    return HTTP_OK;
}
```

**Comment by lpereira** [comment] 2018-11-12 16:15
Will look at it whenever I'm close to my computer. It should be working,
but this code has been refactored so much without tests that there might be
indeed issues.

**Comment by alexhultman** [comment] 2018-11-16 21:01
Did you manage to check this out? I can't get it to work with a completely clean compile.

**Comment by lpereira** [comment] 2020-07-01 07:27
It should be working now, ~2 years later.  The sample app has 3 samples in one now, including a chat app with an internal pub/sub mechanism.

**Closed by lpereira** 2020-07-01 07:27 UTC
Labels: HTTP/Protocol stuff
