### ISSUE TITLE
Segmentation Fault when use float/double type

### ISSUE THREAD

**Issue by 130B848** [lpereira/lwan#203] opened 2017-06-26 16:41 UTC
I use printf function to print a float type number then a segmentation fault happen.
I tried to add one line 
```c
printf("%f\n", 1.0);
```
at the begining of hello_world function in testrunner/main.c,
and the request of /hello would crash.

**Comment by lpereira** [comment] 2017-06-26 16:47
That's unusual.  Could you please share which compiler, architecture, operating system (& version), and if it's a debug or release build?

**Comment by 130B848** [comment] 2017-06-26 16:54
I use gcc 4.9.2 on Debian 8.8 (jessie) x86_64
E5-2620 v4 with 16GB DDR4
Release build is installed.

Another issue is that there are also some errors when I test with "make testsuite",
but I skim the testsuite.py, there should be some error because of exit or exceptions.

Is it my own problem?

Thx for your timely reply :)

**Comment by lpereira** [comment] 2017-06-26 19:42
I'll take a closer look once I get my personal computer fixed.

**Comment by lpereira** [comment] 2017-07-13 06:00
@130B848, it seems that I've fixed the issue with floating point.  Could you please recheck?

As for the "testsuite" errors, could you please open another issue with more details, including which exceptions are being raised?

**Comment by lpereira** [comment] 2017-07-15 19:03
Seems to be a duplicate of #191.

**Comment by lpereira** [comment] 2017-11-03 03:47
This has been hopefully fixed. Please reopen if not an issue any longer.

**Closed by lpereira** 2017-11-03 03:47 UTC
